# See config.example.yml for documentation.
object_base: orig/GNDP8P
object: sys/main.dol
hash: f7df6349739089094409b89bb2e5f7cb54c0a756
symbols: config/GNDP8P/symbols.txt
splits: config/GNDP8P/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 14
quick_analysis: false
